message(STATUS "Trying find vcpkg")
if(DEFINED ENV{VCPKG_ROOT} )
    message(STATUS "===================")
    set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "Vcpkg toolchain file")
    include("${CMAKE_TOOLCHAIN_FILE}")
    message(STATUS "vcpkg found in ${CMAKE_TOOLCHAIN_FILE}" )
    message(STATUS "===================")
else()
    message(STATUS "vcpkg not found" )
endif()